language: node_js

branches:
  only:
    - master
    - /^greenkeeper/.*$/


notifications:
  email: false

node_js:
  - node

script:
  - npm run test:prod
  - npm run build

# after_success:
#   - npm run report-coverage
#   - npm run deploy-docs
#   - npm run semantic-release

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
