language: node_js

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
  directories:
    - ~/.npm
    - ~/.cache

notifications:
  email: false

node_js:
  - node

install:
  - npm ci
  
script:
  - npm run test
  - npm run build

# after_success:
#   - npm run report-coverage
#   - npm run deploy-docs
#   - npm run semantic-release

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
