language: node_js

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
  directories:
    - ~/.npm
    - ~/.cache

notifications:
  email: false

node_js:
  - node

install:
  - npm ci
  
script:
  - npm run test
  - npm run build

