skip_branch_with_pr: true

branches:
  only:
    - master

skip_tags: true

skip_commits:
  files:
    - README.md
    - code-of-conduct.md
    - CONTRIBUTING.md
    - LICENSE
    - .circleci/*
    - .vscode/*

cache:
  - '%AppData%\npm-cache -> appveyor.yml'
  - node_modules -> package-lock.json
  
install:
  - npm install

before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
  - npm run build

test_script:
  - npm run test:prod
