version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2-browsers
    steps:
      - checkout
      - run: npm run build
      - run: npm test
workflows:
  version: 2
  build:
    jobs:
      - build